apiVersion: apps/v1
kind: Deployment
metadata:
  name: pods-nfs
spec:
  selector:
    matchLabels:
      app: pods-nfs
  template:
    metadata:
      labels:
        app: pods-nfs
    spec:
      containers:
      - name: pods-nfs
        image: itsthenetwork/nfs-server-alpine:12
        command:
          - /bin/sh
          - -c
          - |
            adduser -D -g "Pods service user used by Files API to manage NFS folder." -k /dev/null pods &&\
            apk add --no-cache openssh openrc acl &&\
            rc-status &&\
            rc-update add sshd &&\
            touch /run/openrc/softlevel &&\
            setfacl -R -m u:pods:rwx /podsnfs &&\
            mkdir /home/pods/.ssh &&\
            ssh-keygen -f /home/pods/.ssh/podskey -m PEM -q -N '' &&\
            cp /home/pods/.ssh/podskey.pub /home/pods/.ssh/authorized_keys &&\
            ssh-keygen -A &&\
            chown pods:pods /home/pods/.ssh/* &&\
            sed -i 's/#PubkeyAuthentication/PubkeyAuthentication/g' /etc/ssh/sshd_config &&\
            rc-service sshd restart &&\
            /usr/bin/nfsd.sh
        securityContext:
          privileged: true
        env:
        - name: SHARED_DIRECTORY
          value: "/podsnfs"
        ports:
        - name: pods-nfs
          containerPort: 2049
        - name: pods-nfs-ssh
          containerPort: 22
        volumeMounts:
        - name: pods-nfs-vol
          mountPath: "/podsnfs"

      volumes:
      - name: pods-nfs-vol
        persistentVolumeClaim:
          claimName: pods-nfs-vol
