# Granting 'MAKEFILE_SERVICE_NAME-serviceaccount' service account the cluster role 'MAKEFILE_SERVICE_NAME-role' which has
# permissions to list/create/get/watch/delete pods and pods/logs.
# Needed for spawner, worker, and health.
# Must create subject for each namespace you want the role to be binded to.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: MAKEFILE_SERVICE_NAME-serviceaccount
    #automountServiceAccountToken: false

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: MAKEFILE_SERVICE_NAME-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["list", "create", "get", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["list", "get", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["list", "get", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: MAKEFILE_SERVICE_NAME-role
subjects:
- kind: ServiceAccount
  name: MAKEFILE_SERVICE_NAME-serviceaccount
roleRef:
  kind: Role
  name: MAKEFILE_SERVICE_NAME-role
  apiGroup: rbac.authorization.k8s.io
