apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-postgres
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-postgres
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-postgres
    spec:
      containers:
      - name: MAKEFILE_SERVICE_NAME-postgres
        image: postgres:14
        imagePullPolicy: Always
        command: ["docker-entrypoint.sh"]
        args: [
          "-c", "ssl=on",
          "-c", "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem",
          "-c", "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
        ]
        resources:
          requests:
            cpu: ".5"
            memory: "1G"
          limits:
            cpu: "3"
            memory: "3G"
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: pods-admin
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: postgres-password
        - name: PGSSLMODE
          value: "require"
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: pods-postgres-vol
          mountPath: "/pgdata"
      volumes:
      - name: pods-postgres-vol
        persistentVolumeClaim:
          claimName: pods-postgres-vol