
apiVersion: apps/v1
kind: Deployment
metadata:
  name: MAKEFILE_SERVICE_NAME-rabbitmq
spec:
  selector:
    matchLabels:
      app: MAKEFILE_SERVICE_NAME-rabbitmq
  template:
    metadata:
      labels:
        app: MAKEFILE_SERVICE_NAME-rabbitmq
    spec:
      containers:
      - name: MAKEFILE_SERVICE_NAME-rabbitmq
        image: rabbitmq:3.6.12-management
        resources:
          requests:
            cpu: ".5"
            memory: "1G"
          limits:
            cpu: "3"
            memory: "3G"
        ports:
        - name: rabbitmq
          containerPort: 5672
        - name: rabbitmq-dash
          containerPort: 15672
        env:
        - name: RABBITMQ_NODENAME
          value: "MAKEFILE_SERVICE_NAME-rabbitmq"
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "+A 128"
        - name: RABBITMQ_DEFAULT_USER
          value: "pods-admin"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: tapis-MAKEFILE_SERVICE_NAME-secrets
              key: rabbitmq-password
