
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-rabbitmq
spec:
  type: NodePort # Required for multi-namespace connections
  selector:
    app: MAKEFILE_SERVICE_NAME-rabbitmq
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: 5672

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-rabbitmq-dash
spec:
  type: NodePort # Required for local access
  selector:
    app: MAKEFILE_SERVICE_NAME-rabbitmq
  ports:
  - name: rabbitmq-dash
    port: 15672
    targetPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-postgres
spec:
  type: NodePort # Required for multi-namespace connections
  selector:
    app: MAKEFILE_SERVICE_NAME-postgres
  ports:
  - name: MAKEFILE_SERVICE_NAME-postgres
    port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-api
spec:
  type: NodePort # Required for local access
  selector:
    app: MAKEFILE_SERVICE_NAME-api
  ports:
  - name: fastapi
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-api-jupyter
spec:
#DEV  type: NodePort # Required for local access (when DEV_TOOLS is true)
  selector:
    app: MAKEFILE_SERVICE_NAME-api
  ports:
  - name: jupyter
    port: 8888
    targetPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-traefik
spec:
  type: NodePort # Required for local access
  selector:
    app: MAKEFILE_SERVICE_NAME-traefik
  ports:
  - name: traefik
    port: 80
    targetPort: 80
  - name: traefik-dash
    port: 8080
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: MAKEFILE_SERVICE_NAME-nfs
spec:
  type: NodePort # Required for multi-namespace connections
  selector:
    app: MAKEFILE_SERVICE_NAME-nfs
  ports:
  - name: MAKEFILE_SERVICE_NAME-nfs
    port: 2049
    targetPort: 2049
  clusterIP: MAKEFILE_STATIC_NFS_IP