"""init7

Revision ID: 96f8878302f1
Revises: 4e04cfb7cbbe
Create Date: 2024-06-03 08:32:29.116348

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel              ##### Required when using sqlmodel and not use sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f8878302f1'
down_revision = '4e04cfb7cbbe'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_alltenants"]()


def downgrade(engine_name):
    globals()["downgrade_alltenants"]()




def upgrade_alltenants():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template')

def downgrade_alltenants():
    op.create_table('template')
    # ### end Alembic commands ###
