## Neo4j typically has users add plugins via environment variables unfortunately
## once the Neo4j version is too far out of date, that mechanism breaks.
## So I create a neo4j image with plugins pre-installed so we don't break due to upstream.
FROM neo4j:4.4
# Download neosemantics plugin jar
RUN wget -P $PWD/plugins https://github.com/neo4j-labs/neosemantics/releases/download/4.4.0.3/neosemantics-4.4.0.3.jar
# Download APOC plugin jar
RUN wget -P $PWD/plugins https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/4.4.0.12/apoc-4.4.0.12-all.jar

## For s3 via APOC plugin we need some extra jars: 
RUN wget -P $PWD/plugins https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.12.136/aws-java-sdk-core-1.12.136.jar
RUN wget -P $PWD/plugins https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.12.136/aws-java-sdk-s3-1.12.136.jar
RUN wget -P $PWD/plugins https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
RUN wget -P $PWD/plugins https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar 
RUN wget -P $PWD/plugins https://repo1.maven.org/maven2/joda-time/joda-time/2.10.13/joda-time-2.10.13.jar

# s3cmd in case we want to use it manually. :)
RUN apt-get update && apt-get install -y s3cmd
