### Author: Christian Garcia (TACC)
# Description. This Github action runs when there are new commits to `dev`.
# The action logs into Docker with the Github action environment secrets `DOCKERHUB_USERNAME`
# and `DOCKERHUB_TOKEN`.
# The action pulls the repo and builds the tapis/pods-api image
#
# NOVEMBER 29th:
#   DOCKERHUB_USERNAME: username for tuyami
#   DOCKERHUB_TOKEN: token for tuyamei

name: Build & Push - develop
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
    environment: docker

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    environment: docker
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        name: Setup Docker Buildx

      - uses: docker/login-action@v2
        name: Log in to Docker
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date # get the date for the img tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - uses: docker/build-push-action@v3
        name: Build & push tagged Docker backend image
        with:
          push: true
          tags: tapis/pods-api:dev,tapis/pods-api:${{ steps.date.outputs.date }}
